### PR TITLE
Bundled svg icons + minification

### PR DESCRIPTION
**Pull request by samuelg0rd0n**
External SVG icons (as used until now) is not an ideal solution because when this package is bundled in the final project, SVG loader must be used, and for example in case of MyAxiory, there is none. And we don't want to force developers to install additional loaders and/or edit their webpack configs.

From my googling, neither rollup nor any other available rollup plugin can work with `require()` with variables (such as ```require(`./icons/${props.icon}.svg`)```. So I had to rewrite it using dynamic `import()` and plugin `@rollup/plugin-dynamic-import-vars`.

As a bonus, I installed `rollup-plugin-terser` for bundle minification.

Just a thought: I'm wondering if we shouldn't have switched to webpack right from the start because I feel like problems like this will pop up in the future. I'm not saying this wouldn't happen with webpack but it has better community support and we're using it also on other projects. And the larger this project becomes, the more painful it will be to switch.

### CODE REVIEW

**Review by FilipPyrek — CHANGES_REQUESTED** [review]
Agreed with @samuelg0rd0n to refactor this and stop using dynamic imports and replace them with static imports/export for the svg icons.

**Comment by chorobin** [comment]
Just some of my thoughts.

I wonder if SVGR will work if we're importing SVG's in the component library itself? 

https://react-svgr.com/docs/rollup/

Unfortunately you may need to write a type declaration along with the SVG for this

As for NextJS, if you want to use import syntax for importing SVG then the webpack config needs to be changed 👎

However if SVGR converts them to React components and they're in the component library then an SVG could be exported from the component library as a component rather than an SVG?

**Comment by samuelg0rd0n** [comment]
@FilipPyrek Don't be appalled by the number of changes. I just moved the icons folder for component icons to a different location because it seemed more logical this way. And I had to rename the original icons folder.

**Comment by samuelg0rd0n** [comment]
@chorobin I'm sorry, I have to say, I'm not sure what to take out of this. We don't need SVGR or anything like that. We agreed with @FilipPyrek to import all SVGs statically into the bundle (for now) so no SVG loader is needed on the NextJS side at the moment and no webpack config needs to be modified.

**Review by FilipPyrek — APPROVED** [review]

**Pull request merged**
