### PR TITLE
timezone component

### PR DESCRIPTION
**Pull request by brno32**

### CODE REVIEW

**Comment by chromale** [comment]
CleanShot 2021-02-15 at 10 09 46@2x
Code looks okay, but I’m not sure about using Moment library which is deprecated. Can we switch to [date-fns](https://www.npmjs.com/package/date-fns) for example?

**Comment by brno32** [comment]
> Code looks okay, but I’m not sure about using Moment library which is deprecated. Can we switch to [date-fns](https://www.npmjs.com/package/date-fns) for example?

`date-fns` doesn't provide a timezone list, though. It uses some built-in browser features to work with dates, which means certain timezones aren't available in some browsers, and it ultimately doesn't provide a list of timezones.

**Comment by chromale** [comment]
> > Code looks okay, but I’m not sure about using Moment library which is deprecated. Can we switch to [date-fns](https://www.npmjs.com/package/date-fns) for example?
> 
> `date-fns` doesn't provide a timezone list, though. It uses some built-in browser features to work with dates, which means certain timezones aren't available in some browsers, and it ultimately doesn't provide a list of timezones.

Okay. Isn’t there any other library for this we can use? I don’t feel like including a deprecated library is a good idea 🤔

**Comment by brno32** [comment]
> Okay. Isn’t there any other library for this we can use? I don’t feel like including a deprecated library is a good idea 🤔

https://www.npmjs.com/package/countries-and-timezones?

**Comment by chromale** [comment]
> https://www.npmjs.com/package/countries-and-timezones

Seems nice 👍

**Review by tomzaoral — APPROVED** [review]

**Review by jakubhonig-purple — APPROVED** [review]

**Review by chromale — APPROVED** [review]

**Pull request merged**
